"""create color tables

Revision ID: 74897899642e
Revises: 
Create Date: 2026-03-01 10:57:02.190562

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '74897899642e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_color_name'), 'color', ['name'], unique=True)
    op.create_table('color_assign',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color'], ['color.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'color', name='uq_color_assign_key_color')
    )
    op.create_index(op.f('ix_color_assign_color'), 'color_assign', ['color'], unique=False)
    op.create_index(op.f('ix_color_assign_key'), 'color_assign', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_color_assign_key'), table_name='color_assign')
    op.drop_index(op.f('ix_color_assign_color'), table_name='color_assign')
    op.drop_table('color_assign')
    op.drop_index(op.f('ix_color_name'), table_name='color')
    op.drop_table('color')
    # ### end Alembic commands ###
